regression_metric:
  class_path: comet.models.RegressionMetric
  init_args:
    nr_frozen_epochs: 0.3
    keep_embeddings_frozen: True
    optimizer: AdamW
    encoder_learning_rate: 1.0e-06
    learning_rate: 1.5e-05
    layerwise_decay: 0.95
    encoder_model: XLM-RoBERTa
    pretrained_model: xlm-roberta-large
    pool: avg
    layer: mix
    layer_transformation: sparsemax
    layer_norm: False
    loss: mse
    dropout: 0.1
    batch_size: 128
    train_data:
      - /leonardo_work/IscrC_MTMIT/lorenzo/mt_eval_data/da/train/1720-diff-da.csv
    validation_data:
      - /leonardo_work/IscrC_MTMIT/lorenzo/mt_eval_data/da/dev/wmt-ende-newstest2021.csv
      - /leonardo_work/IscrC_MTMIT/lorenzo/mt_eval_data/da/dev/wmt-enru-newstest2021.csv
      - /leonardo_work/IscrC_MTMIT/lorenzo/mt_eval_data/da/dev/wmt-zhen-newstest2021.csv
    hidden_sizes:
      - 3072
      - 1024
    activations: Tanh
    
trainer: ../trainer.yaml
early_stopping: ../early_stopping.yaml
model_checkpoint: ../model_checkpoint.yaml
wandb_logger: ../wandb_logger.yaml
